[tool.poetry]
name = "adventofcode"
version = "0.1.0"
description = ""
authors = ["externref <shiva02939@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
ruff = "^0.8.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
